### ISSUE TITLE
Freetds patch needed for 1.09 [rt.cpan.org #41372]

### ISSUE THREAD

**Issue by mpeppler** [mpeppler/DBD-Sybase#9]
Migrated from [rt.cpan.org#41372](https://rt.cpan.org/Ticket/Display.html?id=41372) (status was 'new')

Requestors:
* sales@minixel.com

From sales@minixel.com on 2008-12-02 12:56:19
:
```
RHEL 64 and Freetds stable. There was a similar patch for version 1.09 
but it does not work on 1.09

gcc -c  -I/usr/include -DNO_CHAINED_TRAN=1 -DNO_THREADS  -DSYB_LP64 -
DNO_BLK=1 -I/usr/lib64/perl5/site_perl/5.8.8/x86_64-linux-thread-
multi/auto/DBI -D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -
Wdeclaration-after-statement -I/usr/local/include -D_LARGEFILE_SOURCE -
D_FILE_OFFSET_BITS=64 -I/usr/include/gdbm -O2 -g -pipe -Wall -Wp,-
D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-
size=4 -m64 -mtune=generic   -DVERSION=\"1.09\" -DXS_VERSION=\"1.09\" -
fPIC "-I/usr/lib64/perl5/5.8.8/x86_64-linux-thread-multi/CORE"   
Sybase.c
Sybase.c: In function XS_DBD__Sybase__db__isdead:
Sybase.c:103: warning: unused variable ix
Sybase.c: In function XS_DBD__Sybase__db__date_fmt:
Sybase.c:121: warning: unused variable ix
Sybase.xs: In function XS_DBD__Sybase__db_ping:
Sybase.xs:83: warning: implicit declaration of function syb_ping
Sybase.xs: In function XS_DBD__Sybase__st_cancel:
Sybase.xs:95: warning: implicit declaration of function syb_st_cancel
Sybase.c:157: warning: unused variable ix
Sybase.c: In function XS_DBD__Sybase__st_ct_get_data:
Sybase.c:175: warning: unused variable ix
Sybase.c: In function XS_DBD__Sybase__st_ct_data_info:
Sybase.c:205: warning: unused variable ix
Sybase.c: In function XS_DBD__Sybase__st_ct_send_data:
Sybase.c:240: warning: unused variable ix
Sybase.c: In function XS_DBD__Sybase__st_ct_prepare_send:
Sybase.c:260: warning: unused variable ix
Sybase.c: In function XS_DBD__Sybase__st_ct_finish_send:
Sybase.c:278: warning: unused variable ix
Sybase.c: In function XS_DBD__Sybase__st_ct_data_info:
Sybase.xs:123: warning: sybaction may be used uninitialized in this 
function
gcc -c  -I/usr/include -DNO_CHAINED_TRAN=1 -DNO_THREADS  -DSYB_LP64 -
DNO_BLK=1 -I/usr/lib64/perl5/site_perl/5.8.8/x86_64-linux-thread-
multi/auto/DBI -D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -
Wdeclaration-after-statement -I/usr/local/include -D_LARGEFILE_SOURCE -
D_FILE_OFFSET_BITS=64 -I/usr/include/gdbm -O2 -g -pipe -Wall -Wp,-
D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-
size=4 -m64 -mtune=generic   -DVERSION=\"1.09\" -DXS_VERSION=\"1.09\" -
fPIC "-I/usr/lib64/perl5/5.8.8/x86_64-linux-thread-multi/CORE"   
dbdimp.c
dbdimp.c:14: error: expected =, ,, ;, asm or __attribute__ before 
FREETDS
dbdimp.c: In function clientmsg_cb:
dbdimp.c:265: warning: value computed is not used
dbdimp.c:286: warning: format %ld expects type long int, but argument 5 
has type int
dbdimp.c:286: warning: format %ld expects type long int, but argument 6 
has type int
dbdimp.c:289: warning: format %ld expects type long int, but argument 5 
has type int
dbdimp.c:289: warning: format %ld expects type long int, but argument 6 
has type int
dbdimp.c: In function servermsg_cb:
dbdimp.c:474: warning: value computed is not used
dbdimp.c:511: warning: format %ld expects type long int, but argument 5 
has type CS_MSGNUM
dbdimp.c:511: warning: format %ld expects type long int, but argument 6 
has type CS_INT
dbdimp.c:514: warning: format %ld expects type long int, but argument 5 
has type CS_INT
dbdimp.c:514: warning: format %ld expects type long int, but argument 6 
has type CS_INT
dbdimp.c: In function syb_init:
dbdimp.c:779: error: BLK_VERSION_150 undeclared (first use in this 
function)
dbdimp.c:779: error: (Each undeclared identifier is reported only once
dbdimp.c:779: error: for each function it appears in.)
dbdimp.c:783: error: BLK_VERSION_125 undeclared (first use in this 
function)
dbdimp.c:787: error: BLK_VERSION_120 undeclared (first use in this 
function)
dbdimp.c:726: warning: unused variable boolean
dbdimp.c: In function get_server_version:
dbdimp.c:1569: warning: unused variable db
dbdimp.c: In function syb_db_opentran:
dbdimp.c:1934: warning: format %x expects type unsigned int, but 
argument 5 has type struct imp_dbh_t *
dbdimp.c: In function syb_db_disconnect:
dbdimp.c:1972: warning: suggest parentheses around assignment used as 
truth value
dbdimp.c: In function dbd_preparse:
dbdimp.c:2467: warning: unused variable STATES
dbdimp.c: In function _convert:
dbdimp.c:3302: warning: suggest parentheses around && within ||
dbdimp.c: In function syb_bind_ph:
dbdimp.c:5064: warning: operation on lna may be undefined
dbdimp.c: In function fetch_data:
dbdimp.c:5193: warning: format %ld expects type long int, but argument 
5 has type CS_INT
make: *** [dbdimp.o] Error 1


```

From sales@minixel.com on 2008-12-02 12:57:37
:
```
There was a patch for 1.08.
http://rt.cpan.org/Ticket/Display.html?id=34411


On Tue Dec 02 07:56:19 2008, falves1 wrote:
> RHEL 64 and Freetds stable. There was a similar patch for version 
1.09 
> but it does not work on 1.09
> 
> gcc -c  -I/usr/include -DNO_CHAINED_TRAN=1 -DNO_THREADS  -DSYB_LP64 -
> DNO_BLK=1 -I/usr/lib64/perl5/site_perl/5.8.8/x86_64-linux-thread-
> multi/auto/DBI -D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -
> Wdeclaration-after-statement -I/usr/local/include -
D_LARGEFILE_SOURCE -
> D_FILE_OFFSET_BITS=64 -I/usr/include/gdbm -O2 -g -pipe -Wall -Wp,-
> D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-
> size=4 -m64 -mtune=generic   -DVERSION=\"1.09\" -DXS_VERSION=\"1.09
\" -
> fPIC "-I/usr/lib64/perl5/5.8.8/x86_64-linux-thread-multi/CORE"   
> Sybase.c
> Sybase.c: In function XS_DBD__Sybase__db__isdead:
> Sybase.c:103: warning: unused variable ix
> Sybase.c: In function XS_DBD__Sybase__db__date_fmt:
> Sybase.c:121: warning: unused variable ix
> Sybase.xs: In function XS_DBD__Sybase__db_ping:
> Sybase.xs:83: warning: implicit declaration of function syb_ping
> Sybase.xs: In function XS_DBD__Sybase__st_cancel:
> Sybase.xs:95: warning: implicit declaration of function syb_st_cancel
> Sybase.c:157: warning: unused variable ix
> Sybase.c: In function XS_DBD__Sybase__st_ct_get_data:
> Sybase.c:175: warning: unused variable ix
> Sybase.c: In function XS_DBD__Sybase__st_ct_data_info:
> Sybase.c:205: warning: unused variable ix
> Sybase.c: In function XS_DBD__Sybase__st_ct_send_data:
> Sybase.c:240: warning: unused variable ix
> Sybase.c: In function XS_DBD__Sybase__st_ct_prepare_send:
> Sybase.c:260: warning: unused variable ix
> Sybase.c: In function XS_DBD__Sybase__st_ct_finish_send:
> Sybase.c:278: warning: unused variable ix
> Sybase.c: In function XS_DBD__Sybase__st_ct_data_info:
> Sybase.xs:123: warning: sybaction may be used uninitialized in this 
> function
> gcc -c  -I/usr/include -DNO_CHAINED_TRAN=1 -DNO_THREADS  -DSYB_LP64 -
> DNO_BLK=1 -I/usr/lib64/perl5/site_perl/5.8.8/x86_64-linux-thread-
> multi/auto/DBI -D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -
> Wdeclaration-after-statement -I/usr/local/include -
D_LARGEFILE_SOURCE -
> D_FILE_OFFSET_BITS=64 -I/usr/include/gdbm -O2 -g -pipe -Wall -Wp,-
> D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-
> size=4 -m64 -mtune=generic   -DVERSION=\"1.09\" -DXS_VERSION=\"1.09
\" -
> fPIC "-I/usr/lib64/perl5/5.8.8/x86_64-linux-thread-multi/CORE"   
> dbdimp.c
> dbdimp.c:14: error: expected =, ,, ;, asm or __attribute__ before 
> FREETDS
> dbdimp.c: In function clientmsg_cb:
> dbdimp.c:265: warning: value computed is not used
> dbdimp.c:286: warning: format %ld expects type long int, but argument 
5 
> has type int
> dbdimp.c:286: warning: format %ld expects type long int, but argument 
6 
> has type int
> dbdimp.c:289: warning: format %ld expects type long int, but argument 
5 
> has type int
> dbdimp.c:289: warning: format %ld expects type long int, but argument 
6 
> has type int
> dbdimp.c: In function servermsg_cb:
> dbdimp.c:474: warning: value computed is not used
> dbdimp.c:511: warning: format %ld expects type long int, but argument 
5 
> has type CS_MSGNUM
> dbdimp.c:511: warning: format %ld expects type long int, but argument 
6 
> has type CS_INT
> dbdimp.c:514: warning: format %ld expects type long int, but argument 
5 
> has type CS_INT
> dbdimp.c:514: warning: format %ld expects type long int, but argument 
6 
> has type CS_INT
> dbdimp.c: In function syb_init:
> dbdimp.c:779: error: BLK_VERSION_150 undeclared (first use in this 
> function)
> dbdimp.c:779: error: (Each undeclared identifier is reported only once
> dbdimp.c:779: error: for each function it appears in.)
> dbdimp.c:783: error: BLK_VERSION_125 undeclared (first use in this 
> function)
> dbdimp.c:787: error: BLK_VERSION_120 undeclared (first use in this 
> function)
> dbdimp.c:726: warning: unused variable boolean
> dbdimp.c: In function get_server_version:
> dbdimp.c:1569: warning: unused variable db
> dbdimp.c: In function syb_db_opentran:
> dbdimp.c:1934: warning: format %x expects type unsigned int, but 
> argument 5 has type struct imp_dbh_t *
> dbdimp.c: In function syb_db_disconnect:
> dbdimp.c:1972: warning: suggest parentheses around assignment used as 
> truth value
> dbdimp.c: In function dbd_preparse:
> dbdimp.c:2467: warning: unused variable STATES
> dbdimp.c: In function _convert:
> dbdimp.c:3302: warning: suggest parentheses around && within ||
> dbdimp.c: In function syb_bind_ph:
> dbdimp.c:5064: warning: operation on lna may be undefined
> dbdimp.c: In function fetch_data:
> dbdimp.c:5193: warning: format %ld expects type long int, but 
argument 
> 5 has type CS_INT
> make: *** [dbdimp.o] Error 1




```

**Comment by mpeppler** [comment]
I believe that this is no longer an issue.
